export default {
    'WELCOME': 'Vítejte',
    'TICKETS': 'Tickety',
    'ARTICLES': 'Článek',
    'ACCOUNT': 'Účet',
    'SUBMIT': 'Odeslat',
    'EMAIL': 'Email',
    'PASSWORD': 'Heslo',
    'REPEAT_PASSWORD': 'Opakujte heslo',
    'LOG_IN': 'Přihlásit',
    'SIGN_UP': 'Registrovat',
    'FORGOT_PASSWORD': 'Zapomenuté heslo',
    'RECOVER_PASSWORD': 'Obnovit heslo',
    'RECOVER_SENT': 'Byl odeslán e-mail s pokyny pro obnovení.',
    'NEW_EMAIL': 'Nový email',
    'FULL_NAME': 'Celé jméno',
    'OLD_PASSWORD': 'Staré heslo',
    'NEW_PASSWORD': 'Nové heslo',
    'REPEAT_NEW_PASSWORD': 'Opakujte nové heslo',
    'BACK_LOGIN_FORM': 'Zpět na přihlašovací formulář',
    'VIEW_ARTICLES': 'Zobrazit články',
    'EDIT_PROFILE': 'Upravit profil',
    'CLOSE_SESSION': 'Odhlásit se',
    'CREATE_TICKET': 'Vytvořit Ticket',
    'TICKET_LIST': 'Seznam Ticketů',
    'SUPPORT_CENTER': 'Centrum podpory',
    'DEPARTMENT': 'Oddělení',
    'AUTHOR': 'Autor',
    'DATE': 'Datum',
    'RESPOND': 'Odpověď',
    'RESPOND_TICKET': 'Odpovědět na Ticket',
    'CLOSE_TICKET': 'Uzavřít ticket',
    'DELETE_TICKET': 'Smazat ticket',
    'NO_ATTACHMENT': 'Bez přílohy',
    'STAFF': 'Operátor',
    'CUSTOMER': 'Uživatel',
    'YES': 'Ano',
    'NO': 'Ne',
    'CANCEL': 'Zrušit',
    'MY_ACCOUNT': 'Můj účet',
    'DASHBOARD': 'Dashboard',
    'USERS': 'Uživatelé',
    'SETTINGS': 'Nastavení',
    'STATISTICS': 'Statistiky',
    'LAST_ACTIVITY': 'Poslední Aktivity',
    'MY_TICKETS': 'Moje Tickety',
    'NEW_TICKETS': 'Nové Tickety',
    'ALL_TICKETS': 'All Tickets',
    'CUSTOM_RESPONSES': 'Vlastní odpověď',
    'CUSTOM_TAGS': 'Vlastní štítek',
    'LIST_USERS': 'Seznam uživatelů',
    'BAN_USERS': 'Blokovaní uživatelé',
    'LIST_ARTICLES': 'Seznam článků',
    'STAFF_MEMBERS': 'Zaměstanci',
    'DEPARTMENTS': 'Oddělení',
    'SYSTEM_PREFERENCES': 'Systémové nastavení',
    'ADVANCED_SETTINGS': 'Rozšířená nastavení',
    'EMAIL_TEMPLATES': 'Šablony emailu',
    'FILTERS_CUSTOM_FIELDS': 'Filtry a vlastní pole',
    'PRIORITY': 'Priorita',
    'NUMBER': 'Číslo',
    'HIGH': 'Vysoká',
    'MEDIUM': 'Střední',
    'LOW': 'Nízká',
    'TITLE': 'Název',
    'CONTENT': 'Obsah',
    'SAVE': 'Uložit',
    'DISCARD_CHANGES': 'Zrušit změny',
    'DELETE': 'Smazat',
    'LANGUAGE': 'Jazyk',
    'OWNER': 'Vlastník',
    'OWNED': 'Vlastnictví',
    'STATUS': 'Status',
    'NONE': 'None',
    'OPENED': 'Otevřen',
    'CLOSED': 'Uzavřen',
    'CLOSE': 'Zavřít',
    'RE_OPEN': 'Znovu otevřít',
    'ASSIGN_TO_ME': 'Přidělte mi to',
    'UN_ASSIGN': 'Nepřiděleno',
    'VIEW_TICKET': 'Zobrazit Ticket',
    'VIEW_TICKET_DESCRIPTION': 'Zkontrolujte si stav vašeho ticketu pomocí čísla ticketu a e-mailu.',
    'SELECT_CUSTOM_RESPONSE': 'Vyberte vlastní odpověď...',
    'WARNING': 'Varování',
    'INFO': 'Informace',
    'ALL_DEPARTMENTS': 'Všechna Oddělení',
    'EMAIL_BANNED': 'Email zablokován',
    'UN_BAN': 'Zrušit blokování',
    'BAN_NEW_EMAIL': 'Blokovat nový email',
    'BAN_EMAIL': 'Blokovat email',
    'EDIT_EMAIL': 'Upravit email',
    'EDIT_PASSWORD': 'Upravit heslo',
    'CHANGE_EMAIL': 'Změnit email',
    'CHANGE_PASSWORD': 'Změnit heslo',
    'NAME': 'Jméno',
    'SIGNUP_DATE': 'Datum registrace',
    'SEARCH_USERS': 'Hledat uživatele...',
    'SEARCH_EMAIL': 'Hledat email...',
    'USER_VIEW_TITLE': 'Uživatelské #{userId}',
    'EDIT_TOPIC': 'Upravit téma',
    'ADD_TOPIC': 'Přidat téma',
    'ICON': 'Ikona',
    'COLOR': 'Barva',
    'ADD_NEW_ARTICLE': 'Přidat nový článek',
    'ADD_ARTICLE': 'Přidat článek',
    'LAST_EDITED_IN': 'poslední úprava {date}',
    'EDIT': 'Upravit',
    'ADD_CUSTOM_TAG': 'Přidat vlastní štítek',
    'NO_RESULTS': 'Žádné výsledky',
    'DELETE_AND_BAN': 'Smazat a zablokovat',
    'STAFF_LEVEL': 'Úroveň personálu',
    'ASSIGNED': 'Přidělené',
    'ASSIGNED_TICKETS': '{tickets} přidělené tickety',
    'CLOSED_TICKETS': '{tickets} uzavřené tickety',
    'LAST_LOGIN': 'Poslední přihlášení',
    'ADD_NEW_STAFF': 'Přidat nový personál',
    'ADD_STAFF': 'Přidat personál',
    'LEVEL': 'Úroveň',
    'LEVEL_1': 'Úroveň 1 (Tickety)',
    'LEVEL_2': 'Úroveň 2 (Tickety + Články)',
    'LEVEL_3': 'Úroveň 3 (TicketY + Články + Personál)',
    'LEVEL_1_DESCRIPTION': 'může odpovídat pouze na tickety a spravovat uživatele.',
    'LEVEL_2_DESCRIPTION': 'může dělat vše co dělá úroveň 1, navíc může vytvářet nebo upravovat články a může vytvářet vlastní odpovědi.',
    'LEVEL_3_DESCRIPTION': 'může dělat vše co dělá úroveň 2, navíc může vytvářet nebo upravovat zaměstnance a může řídit celý systém.',
    'UPDATE_EMAIL': 'Aktualizovat email',
    'UPDATE_PASSWORD': 'Aktualizovat heslo',
    'UPDATE_LEVEL': 'Aktualizovat úroveň',
    'UPDATE_DEPARTMENTS': 'Aktualizovat oddělení',
    'EDIT_STAFF': 'Upravit zaměstnance',
    'ADD_DEPARTMENT': 'Přidat oddělení',
    'UPDATE_DEPARTMENT': 'Aktualizovat oddělení',
    'TRANSFER_TICKETS_TO': 'Přesunout tickety do',
    'COMMENTS': 'Komentáře',
    'DELETE_STAFF_MEMBER': 'Smazat zaměstnance',
    'MAINTENANCE_MODE': 'Údržbový mód',
    'MAINTENANCE_MODE_INFO': 'Systém dočasně vypne systém pro běžné uživatele.',
    'RECOVER_DEFAULT': 'Obnovit výchozí nastavení',
    'SUPPORT_CENTER_URL': 'Support Center URL',
    'SUPPORT_CENTER_TITLE': 'Support Center název',
    'SUPPORT_CENTER_LAYOUT': 'Support Center rozvržení',
    'DEFAULT_TIMEZONE': 'Výchozí časová zóna (GMT)',
    'NOREPLY_EMAIL': 'Noreply Email',
    'SMTP_USER': 'SMTP Uživatelské jméno',
    'SMTP_SERVER': 'SMTP Server',
    'SMTP_PASSWORD': 'SMTP Heslo',
    'IMAP_USER': 'IMAP Uživatel',
    'IMAP_SERVER': 'IMAP Server',
    'IMAP_PASSWORD': 'IMAP Heslo',
    'IMAP_TOKEN': 'IMAP Token',
    'IMAP_TOKEN_DESCRIPTION': 'Tento token slouží k ověření požadavku.',
    'PORT': 'Port',
    'RECAPTCHA_PUBLIC_KEY': 'Recaptcha Veřejný klíč',
    'RECAPTCHA_PRIVATE_KEY': 'Recaptcha Soukromý klíč',
    'ALLOW_FILE_ATTACHMENTS': 'Povolit přílohy',
    'MAX_SIZE_MB': 'Max velikost (MB)',
    'UPDATE_SETTINGS': 'Aktualizovat nastavení',
    'DEFAULT_LANGUAGE': 'Výchozí jazyk',
    'SUPPORTED_LANGUAGES': 'podporované jazyky',
    'SUPPORTED_LANGUAGES_INFO': 'Podporované jazyky, ve kterých se mohou psát tickety.',
    'ALLOWED_LANGUAGES': 'Povolené jazyky',
    'ALLOWED_LANGUAGES_INFO': 'Povolené jazyky jsou jazyky, které může uživatel používat.',
    'SETTINGS_UPDATED': 'Nastavení bylo aktualizováno',
    'ON': 'Zapnuto',
    'OFF': 'Vypnuto',
    'BOXED': 'Boxed',
    'FULL_WIDTH': 'Plná šířka',
    'LOAD_MORE': 'Načti víc',
    'MY_NOTIFICATIONS': 'Moje oznámení',
    'ALL_NOTIFICATIONS': 'Všechna oznámení',
    'VERIFY_SUCCESS': 'Uživatel byl ověřen',
    'VERIFY_FAILED': 'Nelze ověřit',
    'ENABLE_USER_SYSTEM': 'Použijte uživatelský systém pro zákazníky',
    'ENABLE_USER_REGISTRATION': 'Povolit registraci uživatele',
    'INCLUDE_USERS_VIA_CSV': 'Vložit uživatele pomocí souboru CSV',
    'BACKUP_DATABASE': 'Zálohovat databázi',
    'DELETE_ALL_USERS': 'Smazát všechny uživatele',
    'PLEASE_CONFIRM_PASSWORD': 'Pro provedení těchto změn potvrďte heslo',
    'REGISTRATION_API_KEYS': 'Registrační API klíč',
    'NAME_OF_KEY': 'Název klíče',
    'KEY': 'Klíč',
    'ADD_API_KEY': 'Přidej API klíč',
    'NO_KEY_SELECTED': 'Není vybrán žádný klíč',
    'CHECK_TICKET': 'zkontrolovat ticket',
    'ACTIVITY': 'Aktivity',
    'HOME': 'Domů',
    'TICKET_NUMBER': 'Číslo ticketů',
    'NEXT': 'Další',
    'SUBJECT': 'Předmět',
    'SEND_EMAIL_ON_NEW_TICKET': 'Odeslat mail o novém ticketu',
    'STAFF_UPDATED': 'Zaměstnanec byl aktualizován',
    'UPDATE': 'Aktualizace',
    'NEVER': 'Nikdy',
    'HIMSELF': 'Sám',
    'ADD_USER': 'Přidat uživatele',
    'UPLOAD_FILE': 'Nahrát soubor',
    'PRIVATE': 'Soukromé',
    'ENABLE_USER': 'Povolit uživatele',
    'DISABLE_USER': 'Zakázat uživatele',
    'SHOW_CLOSED_TICKETS': 'Zobrazit uzavřené tickety',
    'IMAGE_HEADER_URL': 'URL obrázku záhlaví',
    'IMAGE_HEADER_DESCRIPTION': 'Obrázek, který bude použit jako záhlaví e-mailu',
    'EMAIL_SETTINGS': 'Nastavení Emailu',
    'ADDITIONAL_FIELDS': 'Další pole',
    'NEW_CUSTOM_FIELD': 'Nové vlastní pole',
    'TYPE': 'Type',
    'SELECT_INPUT': 'Vyber vstup',
    'TEXT_INPUT': 'Zadávání textu',
    'OPTION': 'Volba {index}',
    'OPTIONS': 'Volby',
    'FIELD_DESCRIPTION': 'Popis pole (volitelné)',
    'DESCRIPTION_ADD_CUSTOM_TAG': 'zde můžete přidat nový vlastní štítek',
    'CUSTOM_FIELDS': 'Vlastní pole',

    'CHART_CREATE_TICKET': 'Vytvořené tickety',
    'CHART_CLOSE': 'Uzavřené tickety',
    'CHART_SIGNUP': 'Registrace',
    'CHART_COMMENT': 'Odpovědi',
    'CHART_ASSIGN': 'Přidělené',

    //ACTIVITIES
    'ACTIVITY_COMMENT': 'Komentovaný ticket',
    'ACTIVITY_ASSIGN': 'Přidělený ticket',
    'ACTIVITY_UN_ASSIGN': 'Nepřiřazený ticket',
    'ACTIVITY_CLOSE': 'Uzavřený ticket',
    'ACTIVITY_CREATE_TICKET': 'Vytvořený ticket',
    'ACTIVITY_RE_OPEN': 'Znovuotevřený ticket',
    'ACTIVITY_DEPARTMENT_CHANGED': 'Změnit oddělení v ticketu',
    'ACTIVITY_PRIORITY_CHANGED': 'Změnit prioritu ticketu',

    'ACTIVITY_EDIT_SETTINGS': 'upravená nastavení',
    'ACTIVITY_SIGNUP': 'přihlásil',
    'ACTIVITY_ADD_TOPIC': 'přidat téma',
    'ACTIVITY_ADD_ARTICLE': 'přidat článek',
    'ACTIVITY_DELETE_TOPIC': 'smazat téma',
    'ACTIVITY_DELETE_ARTICLE': 'smazat článek',
    'ACTIVITY_EDIT_ARTICLE': 'upravit článek',
    'ACTIVITY_ADD_STAFF': 'přidán zaměstnanec',
    'ACTIVITY_ADD_DEPARTMENT': 'přidáno oddělení',
    'ACTIVITY_DELETE_DEPARTMENT': 'smazáno oddělení',
    'ACTIVITY_EDIT_DEPARTMENT': 'upravit oddělení',
    'ACTIVITY_ADD_CUSTOM_RESPONSE': 'přidat vlastní odpověď',
    'ACTIVITY_DELETE_CUSTOM_RESPONSE': 'smazat vlastní odpověď',
    'ACTIVITY_EDIT_CUSTOM_RESPONSE': 'upravit vlastní odpověď',
    'ACTIVITY_BAN_USER': 'blokovaný uživatel',
    'ACTIVITY_DELETE_USER': 'vymazaný uživatel',
    'ACTIVITY_UN_BAN_USER': 'blokovaný uživatel',

    'SERVER_REQUIREMENTS': 'Požadavky na server',
    'DATABASE_CONFIGURATION': 'Konfigurace databáze',
    'ADMIN_SETUP': 'Admin nastavení',
    'COMPLETED': 'Hotovo',
    'INSTALL_HEADER_TITLE': 'OpenSupports průvodce instalací',
    'INSTALL_HEADER_DESCRIPTION': 'Tento průvodce vám pomůže konfigurovat a instalovat OpenSupports na vašich webových stránkách',
    'SELECT_LANGUAGE': 'Vybrat jazyk',
    'REQUIREMENT': 'Požadavek',
    'VALUE': 'Hodnota',
    'REFRESH': 'Obnovit',
    'USER_SYSTEM': 'Uživatelský systém',
    'PREVIOUS': 'Předchozí',
    'DATABASE_HOST': 'MySQL server',
    'DATABASE_PORT': 'MySQL server port',
    'DATABASE_NAME': 'MySQL název databáze',
    'DATABASE_USER': 'MySQL uživatel',
    'DATABASE_PASSWORD': 'MySQL heslo',
    'ADMIN_NAME': 'Název administrátorského účtu',
    'ADMIN_EMAIL': 'Administrátorský emailový účet',
    'ADMIN_PASSWORD': 'Heslo administrátorského účtu',
    'ADMIN_PASSWORD_DESCRIPTION': 'Zapamatujte si prosím toto heslo. Je nutné pro přístup k panelu admin. Později jej můžete změnit.',
    'INSTALLATION_COMPLETED': 'Instalace kompletní.',
    'INSTALLATION_COMPLETED_DESCRIPTION': 'Instalace OpenSupports je dokončena. Přesměrování na panel administrátora ...',

    'STEP_TITLE': 'Krok {current} z {total} - {title}',
    'STEP_1_DESCRIPTION': 'Vyberte upřednostňovaný jazyk průvodce instalací.',
    'STEP_2_DESCRIPTION': 'Zde jsou uvedeny požadavky na spuštění OpenSupports. Ujistěte se, že jsou splněny všechny požadavky.',
    'STEP_3_DESCRIPTION': 'Vyplňte prosím konfiguraci MySQL databáze.',
    'STEP_4_DESCRIPTION': 'Vyberte prosím předvolby uživatelského systému.',
    'STEP_5_DESCRIPTION': 'Vyplňte prosím obecné předvolby systému.',
    'STEP_6_DESCRIPTION': 'Nakonfigurujte účet správce.',
    'STEP_7_DESCRIPTION': 'Instalace je kompletní.',

    //VIEW DESCRIPTIONS
    'CREATE_TICKET_DESCRIPTION': 'Toto je formulář pro tvorbu ticketů. Vyplňte formulář a pošlete nám své otázky / pochybnosti / návrhy. Náš systém podpory odpoví co nejdříve.',
    'TICKET_LIST_DESCRIPTION': 'Zde naleznete seznam všech ticketů, které jste zaslali na náš tým podpory.',
    'TICKETS_DESCRIPTION': 'Pošlete ticket přes naše centrum podpory a získejte odpověď na vaše otázky, návrhy a problémy.',
    'ARTICLES_DESCRIPTION': 'Podívejte se na naše články o společných otázkách, průvodcích a dokumentaci.',
    'ACCOUNT_DESCRIPTION': 'Všechny vaše tickety jsou uloženy v profilu vašeho účtu. Mějte přehled o všech svých ticketech, které zašlete našemu týmu.',
    'SUPPORT_CENTER_DESCRIPTION': 'Vítejte v našem centru podpory. Můžete nás kontaktovat prostřednictvím systému ticketů. Vaše tickety budou zodpovězeny našimi pracovníky.',
    'CUSTOM_RESPONSES_DESCRIPTION': 'Vlastní reakce jsou automatické reakce na běžné problémy',
    'CUSTOM_TAGS_DESCRIPTION': 'Zde si můžete prohlédnout správu vlastních štítků pro tickety, abyste je mohli lépe identifikovat',
    'MY_TICKETS_DESCRIPTION': 'Zde si můžete prohlédnout tickety, za které zodpovídáte.',
    'NEW_TICKETS_DESCRIPTION': 'Zde si můžete prohlédnout všechny nové tickety, které nejsou nikomu přiřazeny.',
    'ALL_TICKETS_DESCRIPTION': 'Zde si můžete prohlédnout tickety oddělení, která jsou přiřazeny.',
    'TICKET_VIEW_DESCRIPTION': 'Tato ticket byla zaslána zákazníkem. Zde můžete odpovědět nebo přiřadit ticket',
    'BAN_USERS_DESCRIPTION': 'Zde vidíte seznam zakázaných e-mailů, můžete je zrušit nebo přidat další e-maily do seznamu.',
    'LIST_USERS_DESCRIPTION': 'Toto je seznam uživatelů, kteří jsou registrováni v této platformě. Můžete někoho vyhledat, smazat nebo zakázat.',
    'USER_VIEW_DESCRIPTION': 'Zde naleznete všechny informace o uživateli a všechny tickety odeslané uživatelem. Můžete jej také smazat nebo zakázat.',
    'DELETE_USER_DESCRIPTION': 'Uživatel se nebude moci přihlásit a všechny jeho vstupenky budou vymazány. E-mail již nelze použít.',
    'DELETE_TOPIC_DESCRIPTION': 'Odstraněním tématu  budou vymazány všechny články v něm.',
    'EDIT_TOPIC_DESCRIPTION': 'Zde můžete změnit název, ikonu a barvu ikony tématu.',
    'ADD_ARTICLE_DESCRIPTION': 'Zde můžete přidat článek, který bude k dispozici pro každého uživatele. Bude přidán do kategorie {category}.',
    'LIST_ARTICLES_DESCRIPTION': 'Toto je seznam článků, které obsahují informace o našich službách.',
    'ADD_TOPIC_DESCRIPTION': 'Zde můžete přidat téma, které funguje jako kategorie pro články.',
    'DELETE_ARTICLE_DESCRIPTION': 'Chystáte se tento článek smazat navždy.',
    'STAFF_MEMBERS_DESCRIPTION': 'Zde vidíte, kdo jsou vaši zaměstnanci.',
    'ADD_STAFF_DESCRIPTION': 'Zde můžete přidávat zaměstnance do svých týmů.',
    'EDIT_STAFF_DESCRIPTION': 'Zde můžete upravovat informace o zaměstnanci.',
    'MY_ACCOUNT_DESCRIPTION': 'Zde můžete upravovat informace o vás.',
    'DEPARTMENTS_DESCRIPTION': 'Oddělení je skupina, které mohou jít tickety. Používají se pro kategorizaci ticketů. Můžete je přiřadit ostatním zaměstnancům.',
    'MAINTENANCE_MODE_DESCRIPTION': 'Systém podpory je v režimu údržby, takže v tuto chvíli není k dispozici. Vrátíme se co nejdříve.',
    'EMAIL_TEMPLATES_DESCRIPTION': 'Zde můžete upravovat šablony e-mailů, které budou odesílány uživatelům. Nezapomeňte, že dvojité závorky složené závorky označují proměnnou hodnotu. Například, \'name\' představuje uživatelské jméno.',
    'SYSTEM_PREFERENCES_DESCRIPTION': 'Zde můžete upravit předvolby systému.',
    'VERIFY_SUCCESS_DESCRIPTION': 'Uživatel byl ověřen. Nyní se můžete přihlásit.',
    'VERIFY_FAILED_DESCRIPTION': 'Ověření nebylo možné provést.',
    'STATISTICS_DESCRIPTION': 'Zde si můžete prohlédnout statistiky týkající se ticketů a registrací.',
    'ADVANCED_SETTINGS_DESCRIPTION': 'Zde můžete změnit rozšířená nastavení systému. Buďte opatrní, změny, které provedete, nelze změnit.',
    'USER_SYSTEM_DISABLED': 'Uživatelský systém byl zakázán',
    'USER_SYSTEM_ENABLED': 'Uživatelský systém byl povolen',
    'REGISTRATION_DISABLED': 'Registrace byla zakázána',
    'REGISTRATION_ENABLED': 'Registrace byla povolena',
    'ADD_API_KEY_DESCRIPTION': 'Vložte jméno a vygeneruje se registrační klíč.',
    'SIGN_UP_VIEW_DESCRIPTION': 'Zde si můžete vytvořit účet pro naše centrum podpory. Je nutné k zasílání ticketů a zobrazení dokumentů.',
    'EDIT_PROFILE_VIEW_DESCRIPTION': 'Zde můžete upravovat uživatele, změnit svůj e-mail nebo heslo.',
    'ENABLE_USER_SYSTEM_DESCRIPTION': 'Povolit nebo zakázat používání uživatelského systému. Pokud jej zakážete, všichni uživatelé budou smazáni, ale tickety budou uchovány. Pokud to povolíte, budou vytvořeny uživatelé existujících ticketů.',
    'CSV_DESCRIPTION': 'Soubor CSV musí mít 3 sloupce: e-mail, heslo, jméno. Neexistuje žádný limit v počtu řádků. V souboru bude vytvořen jeden uživatel na řádek.',
    'SMTP_SERVER_DESCRIPTION': 'Konfigurace serveru SMTP umožňuje odesílat e-maily. Pokud jej nenakonfigurujete, OpenSupports nebude odesílat žádné e-maily.',
    'IMAP_SERVER_DESCRIPTION': 'Konfigurace serveru IMAP umožňuje aplikaci vytvářet tickety z e-mailů odeslaných do emailové schránky.',
    'ENABLE_USER_DESCRIPTION': 'Tato akce umožňuje uživateli přihlásit se a vytvářet tickety.',
    'DISABLE_USER_DESCRIPTION': 'Uživatel bude deaktivován a nebude se moci přihlásit a vytvářet tickety.',
    'PRIVATE_RESPONSE_DESCRIPTION': 'Tuto reakci uvidí pouze zaměstnanci',
    'PRIVATE_TOPIC_DESCRIPTION': 'Toto téma uvidí pouze zaměstnanci',
    'PRIVATE_DEPARTMENT_DESCRIPTION': 'Toto oddělení uvidí pouze zaměstnanci',
    'EMAIL_SETTINGS_DESCRIPTION': 'Zde můžete upravit nastavení pro příjem a odesílání e-mailů svým zákazníkům.',
    'IMAP_POLLING_DESCRIPTION': 'Kontrola doručené pošty nebude automaticky prováděna službou OpenSupports. Aby bylo možné zpracovávat e-maily, musíte tyto požadavky pravidelně zpracovávat. {url}',
    'NEW_CUSTOM_FIELD_DESCRIPTION': 'Zde můžete vytvořit uživatelské pole pro uživatele, může to být prázdné textové pole nebo pevná sada možností.',
    'CUSTOM_FIELDS_DESCRIPTION': 'Vlastní pole jsou definována jako další pole, která uživatelé mohou vyplnit, aby jim poskytli více informací.',

    //ERRORS
    'EMAIL_OR_PASSWORD': 'Email nebo heslo není správné',
    'EMAIL_NOT_EXIST': 'Email neexistuje',
    'ERROR_EMPTY': 'Špatná hodnota',
    'ERROR_PASSWORD': 'Chybné heslo',
    'ERROR_NAME': 'Chybné jméno',
    'ERROR_TITLE': 'Chybný názec',
    'ERROR_EMAIL': 'Chybný email',
    'ERROR_CONTENT_SHORT': 'Obsah je příliš krátký',
    'PASSWORD_NOT_MATCH': 'Heslo neodpovídá',
    'INVALID_RECOVER': 'Neplatná data pro obnovení',
    'TICKET_SENT_ERROR': 'Při pokusu o vytvoření lístku došlo k chybě.',
    'TICKET_COMMENT_ERROR': 'Při pokusu o přidání komentáře došlo k chybě.',
    'NO_PERMISSION': 'Nemáte oprávnění k přístupu na tuto stránku.',
    'INVALID_USER': 'Uživatelské id je chybné',
    'ERROR_RETRIEVING_TICKETS': 'Při pokusu o načtení ticketů došlo k chybě.',
    'ERROR_RETRIEVING_USERS': 'Při pokusu o načtení uživatelů došlo k chybě.',
    'ERROR_RETRIEVING_BAN_LIST': 'Při pokusu o načtení seznamu zakázaných e-mailů došlo k chybě.',
    'ERROR_BANNING_EMAIL': 'Při pokusu o zákaz e-mailu došlo k chybě.',
    'ERROR_RETRIEVING_ARTICLES': 'Při pokusu o načtení článků došlo k chybě.',
    'ERROR_LIST': 'Vyberte alespoň jednu možnost',
    'ERROR_URL': 'Chybná URL',
    'UNVERIFIED_EMAIL': 'E-mail ještě není ověřen',
    'ERROR_UPDATING_SETTINGS': 'Při pokusu o aktualizaci nastavení došlo k chybě',
    'INVALID_EMAIL_OR_TICKET_NUMBER': 'Neplatné číslo e-mailu nebo ticketu',
    'INVALID_FILE': 'Neplatný soubor',
    'ERRORS_FOUND': 'Nalezené chyby',
    'ERROR_IMAGE_SIZE': 'Žádný obrázek nesmí mít větší velikost než{size} MB',
    'USER_DISABLED': 'Tento účet je zakázán.',
    'INVALID_SYNTAX': 'Neplatná syntaxe.',
    'DEPARTMENT_PRIVATE_TICKETS': 'Toto oddělení má tickety vytvořené členy kteří nejsou ve skupině a nemůže být soukromé',
    'CURRENTLY_UNAVAILABLE': 'Momentálně nedostupné',

    //MESSAGES
    'SIGNUP_SUCCESS': 'Úspěšně jste se zaregistrovali v našem systému podpory.',
    'TICKET_SENT': 'Ticket byl úspěšně vytvořen.',
    'VALID_RECOVER': 'Heslo bylo úspěšně obnoveno',
    'EMAIL_EXISTS': 'Email již existuje',
    'ARE_YOU_SURE': 'Potvrďte akci',
    'EMAIL_WILL_CHANGE': 'Aktuální e-mail bude změněn',
    'PASSWORD_WILL_CHANGE': 'Aktuální heslo bude změněno',
    'EMAIL_CHANGED': 'E-mail byl úspěšně změněn',
    'PASSWORD_CHANGED': 'Heslo bylo úspěšně změněno',
    'OLD_PASSWORD_INCORRECT': 'Staré heslo je nesprávné',
    'WILL_LOSE_CHANGES': 'Neuložili jste. Vaše změny budou ztraceny.',
    'WILL_DELETE_CUSTOM_RESPONSE': 'Vlastní odpověď bude smazána.',
    'WILL_DELETE_DEPARTMENT': 'Oddělení bude smazáno. Všechny tickety budou převedeny na vybrané oddělení.',
    'NO_STAFF_ASSIGNED': 'K tomuto oddělení není přiřazen žádný zaměstnanec.',
    'NO_DEPARTMENT_ASSIGNED': 'Není vám přiřazeno žádné oddělení ticketů.',
    'LEVEL_UPDATED': 'Úroveň byla úspěšně aktualizována.',
    'DEPARTMENTS_UPDATED': 'Oddělení byla úspěšně aktualizována.',
    'FAILED_EDIT_STAFF': 'Při pokusu o úpravu zaměstnance došlo k chybě.',
    'EMAIL_BANNED_SUCCESSFULLY': 'E-mail byl úspěšně zablokován',
    'WILL_DELETE_STAFF': 'Tento zaměstnanec bude smazán a všechny jeho tickety budou nepřiřazeny.',
    'WILL_RECOVER_EMAIL_TEMPLATE': 'Tato e-mailová šablona bude obnovena na výchozí hodnotu tohoto jazyka.',
    'SUCCESS_IMPORTING_CSV_DESCRIPTION': 'Soubor CSV byl úspěšně importován',
    'SUCCESS_DELETING_ALL_USERS': 'Uživatelé byli úspěšně vymazáni',
    'SUCCESSFUL_CONNECTION': 'Úspěšně připojeno',
    'UNSUCCESSFUL_CONNECTION': 'Neúspěšně připojeno',
    'SERVER_CREDENTIALS_WORKING': 'Pověření serveru pracují správně',
    'DELETE_CUSTOM_FIELD_SURE': 'Někteří uživatelé mohou toto pole používat. Opravdu jej chcete smazat?',

    'LAST_7_DAYS': 'Posledních 7 dní',
    'LAST_30_DAYS': 'Posledních 30 dní',
    'LAST_90_DAYS': 'Posledních 90 dní',
    'LAST_365_DAYS': 'Posledních 365 dní',

    'TEST': 'Test',
    'ACTIVITY_COMMENT_THIS': 'ticket byl okomentován ',
    'ACTIVITY_ASSIGN_THIS': 'přidělit ticket ',
    'ACTIVITY_UN_ASSIGN_THIS': 'zrušit přidělení ticketu ',
    'ACTIVITY_CLOSE_THIS': 'přidělit ticket ',
    'ACTIVITY_CREATE_TICKET_THIS': 'založit ticket',
    'ACTIVITY_RE_OPEN_THIS': 'znovuotevřít ticket',
    'ACTIVITY_DEPARTMENT_CHANGED_THIS': 'změnit oddělení ticketu ',
    'ACTIVITY_PRIORITY_CHANGED_THIS': 'změnit prioritu ticketu ',
    'DATE_PREFIX': 'dne',
    'LEFT_EMPTY_DATABASE': 'Pro automatické vytvoření databáze ponechte prázdné',
    'DEFAULT_PORT': 'Ponechte prázdné pokud chcete nastavit výchozí port 3306',
    'REMEMBER_ME': 'Zapamatovat si mě',
    'EMAIL_LOWERCASE': 'email',
    'PASSWORD_LOWERCASE': 'heslo',
    'TEST_SMTP_CONNECTION': 'Test SMTP připojení',
    'SERVER_ERROR': 'Nepodařilo se připojit k serveru.',
    'EMAIL_SERVER_ADDRESS': 'adresa emailového serveru',
    'EMAIL_SERVER_ADDRESS_DESCRIPTION': 'Adresa, kde budou přijímány a odesílány e-maily'
};
